apiVersion: v2
name: s3-backup-sidecar
description: Helm chart for s3-backup-sidecar
type: application
version: 0.1.0
appVersion: "0.1.0"

# License of the packaged application. ArtifactHub reads this annotation.
annotations:
  artifacthub.io/license: Apache-2.0
sources:
  - https://github.com/fabiocicerchia/s3-backup-sidecar
